import type { DealInvestorsPayload } from "./types/deal-investors.types"

/** Sample payload matching the “Macon Portfolio” reference (dev / preview). */
export function getSampleDealInvestorsPayload(): DealInvestorsPayload {
  return {
    kpis: {
      offeringSize: "$6,000,000",
      committed: "$1,625,000",
      remaining: "$0",
      totalApproved: "$1,625,000",
      totalPending: "$0",
      totalFunded: "$1,625,000",
      approvedCount: "13",
      pendingCount: "0",
      waitlistCount: "0",
      averageApproved: "$125,000",
      nonAccreditedCount: "2",
    },
    investors: [
      {
        id: "1",
        displayName: "Rebecca Duffy",
        entitySubtitle: "Individual",
        userDisplayName: "rduffy",
        userEmail: "rebecca.duffy@example.com",
        investorClass: "Class A",
        investorRole: "Sponsor",
        status: "Investment started",
        committed: "$75,000",
        signedDate: "12-Dec-2022",
        fundedDate: "Dec 13, 2022",
        selfAccredited: "Yes",
        verifiedAccLabel: "Not Started",
        contactId: "rebecca_duffy",
        profileId: "individual",
        offeringId: "primary",
        commitmentAmountRaw: "75000",
        extraContributionAmounts: [],
        docSignedDateIso: "2022-12-12",
      },
      {
        id: "2",
        displayName: "Nigam Family LLC",
        entitySubtitle:
          "LLC, corp, partnership, trust, solo 401(k), or checkbook IRA",
        userDisplayName: "anigam",
        userEmail: "contact@nigamfamily.com",
        investorClass: "Class A",
        investorRole: "",
        status: "Funds fully received (complete)",
        committed: "$100,000",
        signedDate: "10-Dec-2022",
        fundedDate: "Dec 11, 2022",
        selfAccredited: "No",
        verifiedAccLabel: "Not Started",
        contactId: "nigam_family",
        profileId: "llc_corp_trust_etc",
        offeringId: "primary",
        commitmentAmountRaw: "100000",
        extraContributionAmounts: [],
        docSignedDateIso: "2022-12-10",
      },
    ],
  }
}
